name: Build Extension

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
  
    - name: Set up Node.js
      uses: actions/setup-node@v4.0.0
      with:
        node-version: '18'
  
    - name: Install dependencies
      run: npm install
    
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Lint codebase
      run: eslint . --fix
    - name: Format codebase
      run: prettier --write

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Build project
      run: npm run build

