name: Deployment

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4.0.0
        with:
          node-version: "20"

      - name: Cache dependencies
        uses: actions/cache@v4.0.2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install --silent

      - name: Lint codebase
        run: pnpm lint

      - name: Build project
        run: pnpm build

      - name: Zip build artifact
        run: cd dist && zip -r digital-awareness.zip .

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: digital-awareness.zip
          path: dist/digital-awareness.zip
          if-no-files-found: error

  publish:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: digital-awareness.zip

      - name: Publish to Chrome Web Store
        uses: mnao305/chrome-extension-upload@v5.0.0
        with:
          file-path: "./digital-awareness.zip"
          extension-id: ${{ vars.EXTENSION_ID}}
          client-id: ${{ secrets.CLIENT_ID }}
          client-secret: ${{ secrets.CLIENT_SECRET }}
          refresh-token: ${{ secrets.REFRESH_TOKEN }}
          publish: true

      - name: Extract extension version
        run: |
          unzip digital-awareness.zip manifest.json
          VERSION=$(jq -r .version manifest.json)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - uses: actions/checkout@v4.1.1
      - name: Create Release
        uses: ncipollo/release-action@v1.14.0
        with:
          artifacts: "./digital-awareness.zip"
          generateReleaseNotes: true
          makeLatest: true
          tag: v${{ env.VERSION }}
          allowUpdates: true
